# Generated by Django 3.1.4 on 2021-01-09 12:17

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Array_2d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_area', models.CharField(default='', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Array_3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_area', models.CharField(default='', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(max_length=100)),
                ('place_sub_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('lng', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('admin_area', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('place_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.place')),
                ('room_source', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('source_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('detail_href', models.TextField(blank=True, default=None, null=True)),
                ('comment_num', models.IntegerField(blank=True, default=None, null=True)),
                ('star', models.IntegerField(blank=True, default=None, null=True)),
                ('source_rating', models.FloatField(blank=True, default=None, null=True)),
                ('pic_link', models.TextField(blank=True, default=None, null=True)),
            ],
            bases=('bot.place',),
        ),
        migrations.CreateModel(
            name='Sightseeing',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.place')),
            ],
            bases=('bot.place',),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.place')),
            ],
            bases=('bot.place',),
        ),
        migrations.CreateModel(
            name='Resturants',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.place')),
                ('nearby_hotel', models.ManyToManyField(related_name='nearby_hotel', to='bot.Hotel')),
            ],
            bases=('bot.place',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='bot.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateField(default=datetime.date.today)),
                ('num_rooms', models.IntegerField(default=0)),
                ('queried_date', models.DateField(default='')),
                ('instant_hrefs', models.TextField(blank=True, default=None, null=True)),
                ('room_recommend', models.CharField(max_length=100)),
                ('room_remainings', models.CharField(max_length=20)),
                ('hot', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='bot.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='bot.hotel')),
            ],
        ),
    ]
