# Generated by Django 3.1.4 on 2021-01-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210109_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='nearby_hotel',
            field=models.ManyToManyField(related_name='nearby_resturant', to='bot.Hotel'),
        ),
    ]
