# Generated by Django 3.1.4 on 2020-12-30 05:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Array_2d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Array_3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(max_length=100)),
                ('place_sub_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lng', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('admin_area', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('place_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='linebot.place')),
                ('room_source', models.CharField(max_length=20)),
                ('source_name', models.CharField(max_length=100)),
                ('detail_href', models.TextField(blank=True)),
                ('comment_num', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('source_rating', models.FloatField(default=0)),
                ('pic_link', models.TextField(blank=True)),
            ],
            bases=('linebot.place',),
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='linebot.place')),
            ],
            bases=('linebot.place',),
        ),
        migrations.CreateModel(
            name='Sightseeing',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='linebot.place')),
            ],
            bases=('linebot.place',),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='linebot.place')),
            ],
            bases=('linebot.place',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='linebot.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='linebot.hotel')),
            ],
        ),
    ]
