# Generated by Django 3.1.4 on 2020-12-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='comment_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='detail_href',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pic_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='source_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
