# Generated by Django 3.1.4 on 2020-12-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linebot', '0002_auto_20201230_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='pic_url',
            new_name='pics',
        ),
    ]
