# Generated by Django 3.1.4 on 2020-12-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot', '0003_auto_20201230_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
